config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pitches, only: [:index, :show] do
    resources :bookings, except: [:index, :destroy]
  end
  resources :bookings, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pitch
end

app/models/pitch.rb
class Pitch < ApplicationRecord
  has_many :bookings
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :pitches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking)
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @pitch = Pitch.find(params[:pitch_id])
    @booking = Booking.new
  end

  def create
    # finding the pitch by pitch_id from the URL
    @pitch = Pitch.find(params[:pitch_id])
    # generating the booking from the params
    @booking = Booking.new(booking_params)
    # adding user_id from current_user (devise)
    @booking.user_id = current_user.id
    # adding pitch.id from the pitch found earlier in DB
    @booking.pitch = @pitch
    # pundit
    authorize @booking
    # saving the new booking record
    if @booking.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to root_path
    authorize @booking
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @pitches = Pitch.all
    @bookings = Booking.all
  end
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  def index
    #skip_authorization
    @pitches = policy_scope(Pitch).geocoded.order(created_at: :desc)
    authorize @pitches
    @search = params["search"]
    if @search.present?
      @address = @search["address"]
      @pitches = Pitch.near(@address, 100)
    end

    # @pitches = Pitch.geocoded
    @markers = @pitches.map do |pitch|
      {
        lat: pitch.latitude,
        lng: pitch.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { pitch: pitch })
      }
    end
  end

  def show
    # skip_authorization
    @pitch = Pitch.find(params[:id])
    authorize @pitch
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<div class="booking-details">
 <%= @booking.pitch.name%>
 <%= @booking.pitch.price%>
 <%= @booking.pitch.address%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Batch398Join2kick</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="background" style="height: 100vh">
<% if user_signed_in? %>

  <div class="search-bar">
      <%= simple_form_for :search, url: pitches_path, method: "GET", html: { class: 'form-inline' } do |f| %>
      <%= f.input :address, label: false, input_html: {size: 50} %>
      <%= f.submit "Search", class: "button", style: "margin-left: 25px;" %>
      <% end %>
  </div>


    <h1 class="h1">Your Bookings</h1>
    <div class="cards-home">
        <% @bookings.each do |booking| %>

          <% if policy(booking).show? %>
            <div class="card-home">
              <img src="<%= booking.pitch.picture %>" class="card-img1" alt="">

              <div class="card-home-info">
                <h3><%= booking.pitch.name %></h3>
                <p><%= booking.pitch.address %></p>
                <div class="price">
                  <p><i class="far fa-calendar-alt"></i>  <%= booking.start_date %><!-- <br> To: <%= booking.end_date %> --></p>
                  <p><%= booking.pitch.price %>€</p>
                </div>
                <p class="card-home-delete"><%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, booking_path(booking), method: :delete, data: { confirm: "Are you sure?"} %></p>
              </div>
            </div>
          <% end %>
      <% end %>
    </div>

</div>


<% else %>

  <%= render "shared/background_image" %>

  <div class="container">
    <div class="header-landing">
      <h1>No idea where to play football?</h1>
      <h2>Book your pitch with just few clicks!</h2>
    </div>
    <%= simple_form_for :search, url: pitches_path, method: "GET", html: { class: 'form-inline' } do |f| %>
      <%= f.input :address, label: false, input_html: {size: 50} %>
      <%= f.submit "Search", class: "button", style: "margin-left: 25px;" %>
    <% end %>
  </div>

<% end %>
</div>

app/views/pitches/_info_window.html.erb
<div>
  <h4><%=pitch.name%><%=link_to "", pitch_path(pitch), class: 'card-link'%></h4>
  <p><%= pitch.address %></p>
  <h5><%= pitch.price %> €</h5>
</div>

app/views/pitches/index.html.erb
<div class="content">
  <div class="card-pitches">
    <% @pitches.each do |pitch| %>
      <div class="card-pitch">
        <% if policy(pitch).index? %>
          <img src="<%= pitch.picture %>" alt="">
          <div class="card-pitch-description">
            <div>
              <h1><%= pitch.name %></h1>
              <p id="address"><%= pitch.address %></p>
            </div>
            <div class="card-pitch-price">
              <h3><%= pitch.price %> €</h3>
            </div>

          </div>
        <% end %>
        <%= link_to "", pitch_path(pitch), class: 'card-link-to-pitch' %>
      </div>
    <% end %>
  </div>

  <div id="map"
    style="width: 100%; height: 100vh;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/pitches/show.html.erb
<div class="banner_show" style="background-image: linear-gradient(rgba(0, 0, 0, 0.55), rgba(0, 0, 0, 0.43)), url(<%= @pitch.picture %>)">
<h2> <%= @pitch.name %> </h2>
</div>
<div>
  <div class="text-center mb-5">
    <h2>Your data</h2>
  </div>
  <div class="container" style="height: 800px;">

    <div class="search-bar mb-5">
      <%= simple_form_for :booking, url: pitch_bookings_path(@pitch), method: "POST", html: { class: 'form-inline' } do |f| %>
      <%= f.input :start_date, as: :string, label: false, input_html: {class: "datepicker", style: "margin-right: 35px;"}  %>
      <%= f.input :end_date, as: :string, label: false, input_html: {class: "datepicker", style: "margin-right: 35px;", id: "secondRangeInput"} %>
      <%= f.submit "Book", class: "button" %>
      <% end %>
    </div>
    <div class="text-center">
      <h3>Total <%= @pitch.price %> €</h3>
    </div>
  </div>
</div>

app/views/shared/_background_image.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0, 0, 0, 0.55), rgba(0, 0, 0, 0.43)), url('https://res.cloudinary.com/dgwgea5k3/image/upload/v1590488834/abigail-keenan-8-s5QuUBtyM-unsplash_v02m1f.jpg')">

app/views/shared/_background_image_show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0, 0, 0, 0.55), rgba(0, 0, 0, 0.43)), url('https://res.cloudinary.com/dgwgea5k3/image/upload/v1590488834/abigail-keenan-8-s5QuUBtyM-unsplash_v02m1f.jpg')"></div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © 2020 Join2Kick, All rights reserved <i class="far fa-futbol"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
<% else %>
  <div class="navbar navbar-expand-sm navbar-dark fixed-top navbar-lewagon">
<% end %>
  <%= link_to image_tag("https://res.cloudinary.com/juliusscloud/image/upload/v1590654591/Join2Kick_a0t56y.png", width: "120"), root_path %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse navbar-login" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My Bookings", root_path, class: "nav-link nav-special" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/dgwgea5k3/image/upload/v1590748374/Unbenannt-1_f0j2bf.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-light" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>